# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org:
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-gruppexamination

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource: "*"

package:
  individually: true

functions:
  getAllBookings:
    handler: functions/getAllBookings/index.handler
    events:
      - httpApi:
          path: "/api/bookings"
          method: GET
  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: "/api/booking/{id}"
          method: DELETE
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: "/api/bookRoom"
          method: POST
  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: "/api/booking/{id}"
          method: PUT

resources:
  Resources:
    bookingsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
